### ISSUE TITLE
В классе GameStore метод containsGame не находит игру добавленную в коллекцию

### ISSUE THREAD

**Issue by jborisovna** [Nolldor1/TeamProject#2]
# Описание
 В классе `GameStore` метод `containsGame` не находит игру добавленную в коллекцию методом `publishGame`

# Локация дефекта
https://github.com/Nolldor1/TeamProject/blob/6a3c1e7f95c5fed23dcc32181bb7b753486cbc15/src/main/java/ru/netology/GameStore.java#L32-L39

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Nolldor1/TeamProject/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java) в IDEA.
2. Запустить [тест](https://github.com/Nolldor1/TeamProject/blob/6a3c1e7f95c5fed23dcc32181bb7b753486cbc15/src/test/java/ru/netology/GameStoreTest.java#L9) `shouldAddGame`.
3. Посмотреть на вывод в консоли.

*Ожидаемый результат:* Метод `containsGame` возвращает `true`. Добавленная ранее игра есть в каталоге. 
*Фактический результат:* Метод `containsGame` возвращает `false`. Добавленной игры нет в каталоге.

# Скриншот
![image](https://user-images.githubusercontent.com/115487930/221471429-be60d2a7-08dd-4ed1-9be4-b0849bba51d0.png)

# Окружение
* **Операционная система:** Windows 10
* **IDE:** Intellij IDEA 2022.2.4 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Nolldor1** [comment]
[Fixed GameStore](https://github.com/Nolldor1/TeamProject/commit/570e023f883c4479b0295e20585823701b0e185f) https://github.com/Nolldor1/TeamProject/issues/1
