### ISSUE TITLE
В классе GameStore метод getSumPlayedTime всегда возвращает 0

### ISSUE THREAD

**Issue by jborisovna** [Nolldor1/TeamProject#3]
# Описание
 В классе `GameStore` метод `getSumPlayedTime` всегда возвращает ноль вместо общего количества проигранного времени всех игроков 

# Локация дефекта
https://github.com/Nolldor1/TeamProject/blob/3dbdfd6aaf6c07b60e21964e63189e3f0157e47b/src/main/java/ru/netology/GameStore.java#L75-L77

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Nolldor1/TeamProject/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java) в IDEA.
2. Запустить [тест](https://github.com/Nolldor1/TeamProject/blob/3dbdfd6aaf6c07b60e21964e63189e3f0157e47b/src/test/java/ru/netology/GameStoreTest.java#L86) `shouldSumPlayedTime`.
3. Посмотреть на вывод в консоли.

*Ожидаемый результат:* 17.
*Фактический результат:* 0.

# Скриншот
![image](https://user-images.githubusercontent.com/115487930/221594349-6bbc3467-f03e-47bc-83b2-fec40ddd3123.png)

# Окружение
* **Операционная система:** Windows 10
* **IDE:** Intellij IDEA 2022.2.4 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Nolldor1** [comment]
[Fixed GameStore](https://github.com/Nolldor1/TeamProject/commit/570e023f883c4479b0295e20585823701b0e185f) https://github.com/Nolldor1/TeamProject/issues/1
