### ISSUE TITLE
В классе GameStore метод getMostPlayer не отображает имя игрока с игровым временем 1 час

### ISSUE THREAD

**Issue by jborisovna** [Nolldor1/TeamProject#4]
# Описание
 В классе `GameStore` метод `getMostPlayer` возвращает `null` вместо имени игрока, если его игровое время 1 час

# Локация дефекта
https://github.com/Nolldor1/TeamProject/blob/3dbdfd6aaf6c07b60e21964e63189e3f0157e47b/src/main/java/ru/netology/GameStore.java#L58-L69

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/jborisovna/ttt/blob/main/voices) в IDEA.
2. Запустить [тест](https://github.com/Nolldor1/TeamProject/blob/3dbdfd6aaf6c07b60e21964e63189e3f0157e47b/src/test/java/ru/netology/GameStoreTest.java#L73) `shouldGetMostPlayerIfPlayingTimeOneHour`.
3. Посмотреть на вывод в консоли.

*Ожидаемый результат:* "player4". 
*Фактический результат:* null.

# Скриншот
![image](https://user-images.githubusercontent.com/115487930/221597757-695d1895-f666-4a30-99ac-b0d6bede009f.png)

# Окружение
* **Операционная система:** Windows 10
* **IDE:** Intellij IDEA 2022.2.4 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Nolldor1** [comment]
[Fixed GameStore](https://github.com/Nolldor1/TeamProject/commit/570e023f883c4479b0295e20585823701b0e185f) https://github.com/Nolldor1/TeamProject/issues/1
