### ISSUE TITLE
В классе GameStore метод addPlayTime не суммирует время для одного игрока

### ISSUE THREAD

**Issue by jborisovna** [Nolldor1/TeamProject#5]
# Описание
 В классе `GameStore` метод `addPlayTime` при добавлении времени не учитывает ранее проведенное в игре время для одного и того же игрока

# Локация дефекта
https://github.com/Nolldor1/TeamProject/blob/3dbdfd6aaf6c07b60e21964e63189e3f0157e47b/src/main/java/ru/netology/GameStore.java#L46-L52

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Nolldor1/TeamProject/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java) в IDEA.
2. Запустить [тест](https://github.com/Nolldor1/TeamProject/blob/3dbdfd6aaf6c07b60e21964e63189e3f0157e47b/src/test/java/ru/netology/GameStoreTest.java#L39) `shouldAddPlayTime`.
3. Посмотреть на вывод в консоли.

*Ожидаемый результат:* "player3".
*Фактический результат:* "player1".

# Скриншот
![image](https://user-images.githubusercontent.com/115487930/221600326-e12eee73-4582-4521-9c76-b836c3d27413.png)

# Окружение
* **Операционная система:** Windows 10
* **IDE:** Intellij IDEA 2022.2.4 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Nolldor1** [comment]
[Fixed GameStore](https://github.com/Nolldor1/TeamProject/commit/570e023f883c4479b0295e20585823701b0e185f) https://github.com/Nolldor1/TeamProject/issues/1
