### ISSUE TITLE
В классе GameStore метод publishGame не выдает исключение, если продублировать установку игры

### ISSUE THREAD

**Issue by jborisovna** [Nolldor1/TeamProject#6]
# Описание
 В классе `GameStore` метод `publishGame` не выдает исключение, если одну и ту же игру установить второй раз.

# Локация дефекта
https://github.com/Nolldor1/TeamProject/blob/3dbdfd6aaf6c07b60e21964e63189e3f0157e47b/src/main/java/ru/netology/GameStore.java#L22-L26

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/Nolldor1/TeamProject/blob/gamestore/src/test/java/ru/netology/GameStoreTest.java) в IDEA.
4. Запустить [тест](https://github.com/Nolldor1/TeamProject/blob/3dbdfd6aaf6c07b60e21964e63189e3f0157e47b/src/test/java/ru/netology/GameStoreTest.java#L30) `shouldNotAddDuplicated`.
5. Посмотреть на вывод в консоли.

*Ожидаемый результат:* Метод выдал исключение, с сообщением, что данная игра уже есть в каталоге. 
*Фактический результат:* Отображается ошибка `RuntimeException to be thrown, but nothing was thrown`.

# Скриншот
![image](https://user-images.githubusercontent.com/115487930/221602486-00c4c761-5579-4ccb-a86a-2e1d5ede4cb2.png)

# Окружение
* **Операционная система:** Windows 10
* **IDE:** Intellij IDEA 2022.2.4 (Community Edition)
* **Java:** OpenJDK 11

**Comment by Nolldor1** [comment]
[Fixed GameStore](https://github.com/Nolldor1/TeamProject/commit/570e023f883c4479b0295e20585823701b0e185f) https://github.com/Nolldor1/TeamProject/issues/1

Также внес небольшую поправку в сам тест
